# Cloudflare Pages configuration
name = "astro2"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Use our custom worker entry
main = "./cloudflare-worker-entry.js"

# Additional worker configuration
[build]
command = "npm run build"

[site]
bucket = "./dist" 