# Cloudflare Pages configuration
name = "astro2"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Let Astro handle its own worker entry
# No need to specify main = "./cloudflare-worker-entry.js" anymore

# Additional worker configuration
[build]
command = "npm run build"

[site]
bucket = "./dist" 